query Me {
    me {
        email
        loggable {
            __typename
            ... on Admin {
                full_name
                display_picture
            }
            ... on Instructor {
                full_name
                display_picture
            }
        }
    }
}
