query getInstructor($slug: String!) {
    instructor(slug: $slug) {
        id
        first_name
        last_name
        bio
        display_picture
        humanized_created_at
        slug
        user {
            id
            email
            status
        }
        locations {
            name
            id
        }
    }
}
